behaviors:
  Among Us:
    trainer_type: ppo
    max_steps: 5.0e7
    time_horizon: 64
    summary_freq: 10000

    hyperparameters:
      batch_size: 128
      beta: 0.005
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.0003
      learning_rate_schedule: linear
      num_epoch: 3    


    network_settings:
      vis_encode_type: simple
      num_layers: 2
      normalize: false
      hidden_units: 256
      memory:
        sequence_length: 64
        memory_size: 128

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        gamma: 0.99
        strength: 0.02
        encoding_size: 256
        learning_rate: 0.0003

environment_parameters:
  level:
    curriculum:
      - name: Lesson0 
        completion_criteria:
          measure: reward
          behavior: Among Us
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.0
        value: 0
      - name: Lesson1 
        completion_criteria:
          measure: reward
          behavior: Among Us
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.0
        value: 1
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Among Us
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.0
        value: 2


